CREATE TABLE shows(id INTEGER, ts_add INTEGER, title TEXT, PRIMARY KEY (id ASC) ON CONFLICT ROLLBACK);
CREATE TABLE show_sets(id INTEGER, desc BLOB, PRIMARY KEY (id ASC) ON CONFLICT ROLLBACK);
CREATE TABLE show_set_in(id INTEGER, show_id INTEGER, PRIMARY KEY (id, show_id) ON CONFLICT ROLLBACK);
CREATE TABLE episodes(id INTEGER, show_id INTEGER, idx INTEGER, ts_add, length INTEGER, PRIMARY KEY (id ASC) ON CONFLICT ROLLBACK, UNIQUE (show_id, idx) ON CONFLICT ROLLBACK);
CREATE TABLE show_aliases(id INTEGER, alias TEXT, PRIMARY KEY (id, alias) ON CONFLICT ROLLBACK);
